//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/InputSystem/spawnControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SpawnControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SpawnControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""spawnControl"",
    ""maps"": [
        {
            ""name"": ""SaveGame"",
            ""id"": ""6cc469de-86c6-4fe8-9db7-8919189c35fe"",
            ""actions"": [
                {
                    ""name"": ""Save"",
                    ""type"": ""Button"",
                    ""id"": ""769ed57e-3ec3-400b-baf4-2baa711b7e81"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5401068f-914b-4be9-bc4e-d3e9228b039d"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Save"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SaveGame
        m_SaveGame = asset.FindActionMap("SaveGame", throwIfNotFound: true);
        m_SaveGame_Save = m_SaveGame.FindAction("Save", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SaveGame
    private readonly InputActionMap m_SaveGame;
    private List<ISaveGameActions> m_SaveGameActionsCallbackInterfaces = new List<ISaveGameActions>();
    private readonly InputAction m_SaveGame_Save;
    public struct SaveGameActions
    {
        private @SpawnControl m_Wrapper;
        public SaveGameActions(@SpawnControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @Save => m_Wrapper.m_SaveGame_Save;
        public InputActionMap Get() { return m_Wrapper.m_SaveGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SaveGameActions set) { return set.Get(); }
        public void AddCallbacks(ISaveGameActions instance)
        {
            if (instance == null || m_Wrapper.m_SaveGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SaveGameActionsCallbackInterfaces.Add(instance);
            @Save.started += instance.OnSave;
            @Save.performed += instance.OnSave;
            @Save.canceled += instance.OnSave;
        }

        private void UnregisterCallbacks(ISaveGameActions instance)
        {
            @Save.started -= instance.OnSave;
            @Save.performed -= instance.OnSave;
            @Save.canceled -= instance.OnSave;
        }

        public void RemoveCallbacks(ISaveGameActions instance)
        {
            if (m_Wrapper.m_SaveGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISaveGameActions instance)
        {
            foreach (var item in m_Wrapper.m_SaveGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SaveGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SaveGameActions @SaveGame => new SaveGameActions(this);
    public interface ISaveGameActions
    {
        void OnSave(InputAction.CallbackContext context);
    }
}
